.github/workflows/test.yml
README.md
agent/llama_guard.py
agent/research_assistant.py
pyproject.toml

- Make GROQ_API_KEY optional
- Ensure `pytest` has no dependencies on external ENV using pytest-env
- Small cleanups on LlamaGuard

Simplify ENV requirements

---

src/streamlit_app.py

Currently, clicking 1 star for feedback results in `st.feedback()` returning `0` (see https://docs.streamlit.io/develop/api-reference/widgets/st.feedback), and this `if` is not entered:
https://github.com/JoshuaC215/agent-service-toolkit/blob/fbf072de05a8a5ea911fc484a0e8c0516dab8ea4/src/streamlit_app.py#L264-L269

Also allow feedback of 1 star

---

README.md
pyproject.toml
src/agent/research_assistant.py
src/schema/__init__.py
src/schema/schema.py
src/service/service.py
src/streamlit_app.py
uv.lock

I have created a pull request to support Claude (Anthropic) models. Without streaming, it was as straightforward as #37 . With streaming, it was slightly more complicated. Until now, all example models' streamed and final messages had a string content. 
However, Langchain's BaseMessage allows `content: Union[str, List[Union[str, Dict]]]` and our `schema.ChatMessage` content allows only `str` and Anthropic uses the `Dict` variant in streaming mode. @JoshuaC215 I was already wondering about this before,  @JoshuaC215 , could you please shed some light on the reasons for this decision?
For now, I have created a helper method in schema to convert the content to string if necessary (applies both to streamed tokens and final messages). I would note that:
- It can parse only textual content for …

Add claude model example

---

pyproject.toml
src/agent/llama_guard.py
src/agent/research_assistant.py
src/agent/tools.py
src/client/client.py
src/run_client.py
src/run_service.py
src/schema/__init__.py
src/schema/schema.py
src/schema/test_schema.py
src/service/service.py
src/service/test_service.py
src/streamlit_app.py

Due to the mixing of built-in imports and third-party imports, it is difficult to distinguish the source of the packages.
Used the "I" series rules in ruff (an operation similar to isort) to solve this issue.
All the code in this PR was modified using `ruff check --fix`, and future checks can be done through pre-commit.

Add the "I" series rules in ruff (isort operation)

---

pyproject.toml
src/agent/llama_guard.py
src/client/client.py
src/schema/schema.py
src/service/service.py
src/streamlit_app.py

Since both this project and ruff explicitly specify the minimum version as 3.10, it is hoped that syntax can be enhanced based on this version.
[documentation](https://docs.python.org/3/library/typing.html#deprecated-aliases)
[UP006](https://docs.astral.sh/ruff/rules/non-pep585-annotation/) deprecated in 3.9
[UP007](https://docs.astral.sh/ruff/rules/non-pep604-annotation/) support in 3.10
[UP035](https://docs.astral.sh/ruff/rules/deprecated-import/) deprecated in 3.9
All the code in this PR was modified using ruff check --fix, and future checks can be done through pre-commit.

Add the "U" series rules in ruff (pyupgrade)

---

src/service/service.py

The current API places Bearer authentication at the middleware layer, which prevents direct access to the API documentation from a browser when an API KEY is set.
Additionally, the need to provide this API KEY is not mentioned in the API documentation.
I used the built-in features of FastAPI to implement this functionality and removed the middleware that provided the same functionality.
Additionally, because I wanted to allow access to `docs`, `redoc`, and `openapi.json` without providing an API KEY, I set up an extra APIRouter.
docs:
redoc:
---
If you agree with this change, I can add the corresponding tests.
However, the existing tests will fail when an API KEY is provided, so the old tests will need to be adjusted accordingly.
I believe that as the codebase grows, this project needs …

feat: add HTTPBearer check

---

src/service/service.py

Message handling in `/stream` was broken when a node returns multiple messages - only the last one was being streamed. This would only occur in the case of parallel tool calls for the provided agent.
Fixed by correctly yielding each message returned by the node during iteration instead of only the last one.
Fixes #67

Fix bug where only one parallel tool call returned

---

docker/Dockerfile.app
requirements.txt
src/run_client.py
src/schema/__init__.py
src/schema/schema.py
src/schema/test_schema.py
src/service/service.py
src/service/test_utils.py
src/service/utils.py

Remove the dependency to install LangChain to use the schema / client.
Most of the work was cleaning up the from_langchain / to_langchain methods on ChatMessage. The to_langchain code was removed, from_langchain was converted to service.utils.langchain_to_chat_message.
Verified it works by switching Dockerfile.app to only install the requirements.txt which no longer includes LC
"Vendored" a few small pieces of LangChain code to make this work:
- langchain_core.messages.BaseMessage.pretty_print added to ChatMessage
- ToolCall definition copied into schema

Remove langchain dependency from schema.ChatMessage

---

README.md
pyproject.toml
src/agents/models.py
src/streamlit_app.py
uv.lock

This pull request includes changes to add support for AWS Bedrock models and update dependencies accordingly. The most important changes include updates to configuration files, dependency management, and model initialization logic.
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R114-R117): Added instructions for enabling AWS Bedrock models with a new `USE_AWS_BEDROCK` environment variable.
* [`src/agents/models.py`](diffhunk://#diff-40370f67f79320e3bdc1a5067ad6bcb62027f032e44028f6e50c102a83fd0dd1L2-R7): Imported `ChatBedrock` from `langchain_aws` and added logic to initialize the `bedrock-haiku` model when `USE_AWS_BEDROCK` is set to true. [[1]](diffhunk://#diff-40370f67f79320e3bdc1a5067ad6bcb62027f032e44028f6e50c102a83fd0dd1L2-R7) …

Add AWS Bedrock model support and update dependencies

---

src/schema/task_data.py

I have discovered a bug introduced by the task container status evaluation cleanup. In the cleaned-up implementation, Task container's status was `running` only until there was **at least one** completed child Task. That is contrary to the comment stating that `Status is running until **all tasks** have completed`, which is the intended implementation. Fix attached.

Fix task status evaluation

---

.env.example
requirements.txt
src/streamlit_app.py

With #86 we introduced much easier cases where the ENV setup of the streamlit app and the service could get out of sync, specifically with setting the host and port of the service.
This should fix some of those cases so you get the expected behavior more easily especially right after cloning the repo and doing minimal tweaks on `.env`.
Closes #108

Fix issue with ENV mismatch between app and service

---

.github/workflows/test-docker.yml
.github/workflows/test.yml
README.md
docker/Dockerfile.app
pyproject.toml
requirements.txt
uv.lock

Streamlit Community Cloud now supports installing dependencies from `uv.lock` (https://github.com/streamlit/streamlit/issues/9502). With this update, I no longer need to maintain a separate `requirements.txt` file just for streamlit (which was confusing and error prone). However, I still want to keep track of the minimal dependencies to run the client and app separate from the service.
This PR:
- Removes `requirements.txt` which was tracking the client-only dependencies used in Streamlit Cloud
- Adds a dependency group ([PEP 735](https://peps.python.org/pep-0735/)) for tracking the client dependencies, and use that to install the setup for the test-docker Github Action. This uses the `--only-group` flag in uv sync ([ref](https://docs.astral.sh/uv/concepts/projects/dependencies/#development …

Migrate from requirements.txt to a client dependency group

---

README.md
src/agents/__init__.py
src/agents/agents.py
src/agents/research_assistant.py
src/client/__init__.py
src/client/client.py
src/core/settings.py
src/run_client.py
src/schema/__init__.py
src/schema/schema.py
src/service/service.py
src/streamlit_app.py
tests/app/conftest.py
tests/app/test_streamlit_app.py
tests/client/conftest.py
tests/client/test_client.py
tests/core/test_settings.py
tests/integration/test_docker_e2e.py
tests/service/conftest.py
tests/service/test_service.py
tests/service/test_service_e2e.py

This ended up being a big update!
- Introduce `schema.ServiceMetadata` which describes available agents, models, and default values based on the configuration (e.g. available LLM API keys)
- Introduce `/info` endpoint on the service to return the current metadata
- Update the `AgentClient` to retrieve the metadata by default and store it at `AgentClient.info` for use
- Update the Streamlit app to use the `agent_client.info` to set the available agents and models in the app settings
- While I was at it, refactored the error handling in `AgentClient` to be more idiomatic / robust / specific, and updated the app to give cleaner errors when there are connectivity issues
- Updated many tests to work based on all the changes above, and added tests for new functionality
- Now, with the dynamic …

Add an endpoint for service metadata and use it to configure the app

---

pyproject.toml
src/core/llm.py
src/schema/models.py
uv.lock

- Bump the large groq model from llama 3.1 70b to llama 3.3 70b as the former is deprecated by Groq
- Bump DDG-Search to latest

Misc updates

---

src/streamlit_app.py
tests/app/test_streamlit_app.py

_[Originally #124 - thank you @fedebotu for this great contribution!!]_
This PR adds the following improvements:
Previously, a user had to manually copy the `thread_id` to the service URL and set it as a query parameter. Now, a new dialog appears that allows users to conveniently copy the full link for sharing/resuming chats:
If the user tried for any reason to open a new chat with a `thread_id` with no messages yet, the below error appeared:
This PR fixes this issue by simply checking whether there is any history. If there is not, a simple error popup appears, avoiding the crash:

Add Chat Sharing Dialog & BugFix Empty History

---

.env.example
.github/workflows/test.yml
README.md
compose.yaml
src/client/client.py
src/core/settings.py
src/streamlit_app.py
tests/client/test_client.py
tests/core/test_settings.py
tests/integration/test_docker_e2e.py
tests/service/conftest.py

Users reported various compatibility issues with running and accessing the service on `http://localhost:80` by default. Hopefully address those by switching to `0.0.0.0:8080` by default.

Migrate defaults to HOST=0.0.0.0 PORT=8080

---

.env.example
README.md
pyproject.toml
src/core/llm.py
src/core/settings.py
src/schema/models.py
tests/core/test_llm.py
uv.lock

This PR adds experimental support for Ollama to run open models locally alongside agent service toolkit. Currently only one model can be accessed using Ollama at a time.
- `OLLAMA_MODEL` env to set the model to be used with Ollama
- `OLLAMA_BASE_URL` optional env if connecting to Ollama server
- Rough instructions for configuring Ollama (I did some local testing, they may need improvement)
Closes #137

Add ollama support (experimental)

---

src/agents/chatbot.py

Roughly following the example in https://langchain-ai.github.io/langgraph/how-tos/persistence-functional/
But sticking with the `"messages"` key to maintain API compatibility with the other agents.

Switch chatbot to use the langgraph Functional API

---

src/client/client.py
src/service/service.py
src/streamlit_app.py

Few small fixes
- handle service error case where node updates are empty during streaming (#198)
- Client returns an error chat message when streaming errors instead of stack trace
- Clean up sidebar new chat button

Bugfix for empty updates, error handling, sidebar cleanup

---

src/service/service.py
tests/service/test_service_streaming.py

I've observed that the model's final response sometimes arrives in multiple fragments instead of a single complete message. This behavior complicates downstream processing, as the system expects a fully assembled message.
Here’s an example of the issue observed in the logs:
<details>
<summary>Log</summary>
```commandLine
2025-04-29 10:54:30 ====== STREAM EVENT ======
2025-04-29 10:54:30 type: <class 'tuple'>
2025-04-29 10:54:30 repr: ('content', "HERE'S THE LONG CONTENT")
2025-04-29 10:54:30 pprint:
2025-04-29 10:54:30 ('content',
2025-04-29 10:54:30  'HERE'S THE LONG CONTENT'
2025-04-29 10:54:30  '\n'
2025-04-29 10:54:30  '...')
2025-04-29 10:54:30 ==========================
2025-04-29 10:54:30 [2025-04-29 07:54:30 +0000] [1] [ERROR] [/app/service/service.py:238] Error parsing message: …
```

Reassemble partial `AIMessage` fragments from streamed tuples

---

src/agents/llama_guard.py
src/core/llm.py
src/schema/models.py
tests/core/test_llm.py

Groq is deprecating Llama-Guard-3 in June so migrating to the latest

Bump llama-guard to 4-12B

---

pyproject.toml

The May 10, 2025 release introduced an issue on Windows.  It appears langchain-chroma ~=0.2.3 caused the following error when running `uv sync --frozen`
```
Resolved 217 packages in 217ms
error: Distribution `onnxruntime==1.22.0 @ registry+https://pypi.org/simple` can't be installed because it 
doesn't have a source distribution or wheel for the current platform
hint: You're on Windows (`win_amd64`), but `onnxruntime` (v1.22.0) only has wheels for the following 
platforms: `manylinux_2_27_aarch64`, `manylinux_2_27_x86_64`, `manylinux_2_28_aarch64`, 
`manylinux_2_28_x86_64`, `macosx_13_0_universal2`
```
After a little testing, it appears setting the version in the pyproject.toml for "onnxruntime ~= 1.21.1" cleared up the issue.  
An issue for this problem was created a few days ago: …

Correct a 'uv sync' issue on Windows introduced with the Chroma dependency

---

src/schema/models.py

After retesting, it was discovered that the model name used for 2.5 Flash was incorrect. This update corrects the model name to ensure proper identification and functionality.

Fix incorrect model name for 2.5 Flash

---

.env.example
pyproject.toml
src/core/settings.py
src/service/service.py
uv.lock

_copied from #226_
This PR adds optional support for [Langfuse](https://www.langfuse.com/) tracing. Since we use Langfuse internally, this integration allows us to trace all agent calls when the LANGFUSE_TRACING environment variable is set to true.
In addition:
• A Langfuse check has been added to the /health endpoint.
To preserve existing behavior, the endpoint still returns healthy regardless of Langfuse status, but includes an additional langfuse field in the response payload when enabled.

Add Langfuse Tracing Support (Optional via LANGFUSE_TRACING)

---

.gitignore
README.md
langgraph.json
pyproject.toml
src/agents/bg_task_agent/bg_task_agent.py
src/agents/chatbot.py
src/agents/interrupt_agent.py
src/agents/knowledge_base_agent.py
src/agents/langgraph_supervisor_agent.py
src/agents/rag_assistant.py
src/agents/research_assistant.py
uv.lock

Improve out of the box support for Langgraph Studio, based on discussion in https://github.com/JoshuaC215/agent-service-toolkit/discussions/236
- Fix the dependencies in `langgraph.json`
- Add missing .gitignore
- Remove the hard coded checkpointer and store in all the agents
- Install langgraph-cli as part of dev dependencies
- Update README

Improve Langgraph Studio support

---

.env.example
src/core/settings.py
src/memory/postgres.py

When using Postgres as your checkpointer and memory store, AST connects to Postgres at startup time. If those connections are ever closed (timeout, network interruption, postgres restart), the toolkit does not attempt to reconnect. Your easiest recourse is to restart the toolkit.
LangGraph’s Postgres Checkpointer added support for connection pools in [Release checkpointpostgres==1.0.4 · langchain-ai/langgraph](https://github.com/langchain-ai/langgraph/releases/tag/checkpointpostgres%3D%3D1.0.4)
This PR changes AST Postgres memory to use connection pools so that connection management will be abstracted away.
The number of connections is configurable based on `POSTGRES_MIN_CONNECTIONS_PER_POOL` and `POSTGRES_MAX_CONNECTIONS_PER_POOL` environment variables. Default is 1 connection so that …

Postgres Checkpointer and Memory Needs More Resilient Database Connections

---

src/client/client.py

Fixes RuntimeError: 'generator didn't stop after athrow()' that occurs when Claude sends empty string tokens before tool calls in streaming mode.
The issue was that empty string tokens ('') were being yielded to the async generator, causing it to crash when Streamlit tried to process them.
Solution: Skip yielding empty string tokens while preserving all other content and tool execution functionality.
This enables Claude models to properly execute tool calls in streaming mode.

Fix Claude streaming generator error with empty tokens

---

src/schema/schema.py
src/service/service.py
tests/service/test_service.py

Prior to this, if you make a request directly to the service, and don't specify a model, it's hardcoded to gpt-4o-mini, even if there's a different default model configured in the service. This makes it more consistent (IMO) by using the setting for the default model

Use the default model configured in the service if one isn't passed in the request
