JoshuaC215/agent-service-toolkit

- README.md
- agent/research_assistant.py
- requirements.txt
- service/service.py
- Update to langgraph 0.2 and install checkpoint / checkpoint-sqlite
- Fix relevant import paths
Closes #2
> Update to langgraph 0.2 compatibility

- .github/workflows/test.yml
- agent/research_assistant.py
- agent/tools.py
On each pull request push and push to main:
- install environment with uv
- run pylint
- run pytest
> Add CI for testing

- compose.yaml
- pyproject.toml
- src/agent/llama_guard.py
- src/service/service.py
> Switch to astream_events to support token-level streaming with Gemini

- pyproject.toml
- src/agent/research_assistant.py
- src/streamlit_app.py
- uv.lock
Hello @JoshuaC215 , as per discussion in #30 , I have created a pull request to add Gemini as an example. For this to work, you 
GOOGLE_API_KEY environment variable is required if model is to work properly, you can get Gemini API key in Google AI Studio, [see here](https://ai.google.dev/gemini-api/docs/api-key).
> Add Gemini to examples

- src/schema/__init__.py
- src/schema/schema.py
- src/service/service.py
1. Add FeedbackResponse Response
1. Add SSE Response
> Enhance the API documentation.

- src/run_service.py
> feat: Add dev mode

- src/agent/research_assistant.py
- src/service/service.py
- src/service/test_service.py
> refactor: Correct type hint

- README.md
- src/agent/research_assistant.py
OpenAI model optional and Update README.md
> OpenAI model optional

- src/client/client.py
- src/schema/__init__.py
- src/schema/schema.py
- src/service/service.py
- src/service/test_service.py
- src/streamlit_app.py
Draft PR for #52 to get an idea what needs to be done for basic functionality.
> Chat History

- src/schema/__init__.py
- src/schema/schema.py
- src/service/service.py
> Remove AgentResponse, clarify /stream behavior

- src/streamlit_app.py
It's been common for a while to see a bug in the app deployed to Streamlit Cloud where it starts throwing errors related to class type mismatch after a code change. The issue is always resolved after restart.
This has been reported a few times e.g. https://github.com/JoshuaC215/agent-service-toolkit/issues/65 and https://github.com/JoshuaC215/agent-service-toolkit/discussions/47
I have a hypothesis that the issue occurred because the app was caching the AgentClient instance which then got out of sync with the new code somehow (e.g. some bytecode around the class type or something). This would only happen on Streamlit Cloud since it updates the app "live" and maintains the cache. I've never been able to repro it locally (you could probably do it with hot reloading).
This PR updates to keep …
> Fix class type bug in Streamlit app (?)

- src/schema/schema.py
Implement proposal from https://github.com/JoshuaC215/agent-service-toolkit/issues/49#issuecomment-2439652701
> Add custom ChatMessage type

- src/service/service.py
Fixes https://github.com/JoshuaC215/agent-service-toolkit/security/code-scanning/1
> Service: log errors instead of returning details

- src/agents/utils.py
- src/schema/schema.py
- src/service/service.py
- src/streamlit_app.py
- Add a CustomData class in agents/ for sending custom messages either as a node output or custom event
- Add a selectbox in the streamlit app for picking the agent to run
> Implement CustomData for agents; select agent in app

- src/service/service.py
Use multiple decorators to simplify the code instead of re-implementing multiple functions.
> route decorator cleanup

- src/agents/research_assistant.py
> Switch from IsLastStep to RemainingSteps for research_assistant

- .env.example
- src/core/llm.py
- src/core/settings.py
- src/schema/models.py
- src/schema/schema.py
feature by issue #133
- add Deepseek LLM：deepseek-chat
Please review 😄
> add llm deepseek-chat 

- README.md
I added a new video walkthrough - update the README to use the new link
https://www.youtube.com/watch?v=pdYVHw_YCNY
> Update the link to the latest video

- .env.example
- compose.yaml
- docker/Dockerfile.service
- pyproject.toml
- src/core/settings.py
- src/memory/__init__.py
- src/memory/postgres.py
- src/memory/sqlite.py
- src/run_service.py
- src/service/service.py
- uv.lock
Hello @JoshuaC215 ,
Thank you for this implementation. Was really helpful to get started faster.
Thought adding a Postgresql checkpointer to the current implementation might be useful for enterprise use cases when we deploy this solution on cloud.
Could you please review and share your thoughts ?
Regards,
Chengaiah
> Postgresql checkpointer support.

- .env.example
- src/core/llm.py
- src/core/settings.py
- src/schema/models.py
- tests/app/test_streamlit_app.py
- tests/core/test_settings.py
This PR adds support for Azure OpenAI model deployments. To keep things scalable the model deployment names are provided as a mapping in the `.env` file.
> Add Azure OpenAI support with comprehensive configuration

- .env.example
https://docs.smith.langchain.com/observability/how_to_guides/trace_with_langgraph
> Update .env.example to latest Langsmith ENV

- src/agents/agents.py
- src/agents/interrupt_agent.py
- src/run_agent.py
- src/service/service.py
- src/streamlit_app.py
- tests/app/test_streamlit_app.py
- tests/service/conftest.py
- tests/service/test_service.py
[interrupts are the recommended method](https://langchain-ai.github.io/langgraph/concepts/human_in_the_loop/#interrupt) for human in the loop behavior (data validation, confirming action to take, etc.).  I've enhanced this codebase to support basic interrupts (where the inputs and outputs are simple strings).  More advance interrupts handling (ex. interrupt value or response is JSON payload) requires further customization, but I'm trying to keep this simple so somebody can expand if/when they need to.
> Interrupt handling

- src/service/service.py
> Supervisor bugfix

- .env.example
- src/core/llm.py
- src/core/settings.py
- src/schema/models.py
Add an OpenAI-compatible configuration to allow new models (such as local LM-Studio) to be quickly added for testing
> Add openai compatible

- src/memory/__init__.py
- src/memory/postgres.py
- src/memory/sqlite.py
First part of fixes for mypy.
Fixes partially: https://github.com/JoshuaC215/agent-service-toolkit/issues/199
Before:
```
Found 88 errors in 17 files (checked 31 source files)
```
After:
```
Found 84 errors in 16 files (checked 31 source files)
```
> Fix typing in memory module

- src/agents/interrupt_agent.py
- src/service/service.py
* Error handling that may help with #198 
* Fix birthday extraction format issue in interrupt agent
> Improve error handling for interrupt, fix format

- src/streamlit_app.py
- tests/app/test_streamlit_app.py
New chats can be easily created without refreshing the browser
> Feat: add "new chat" button

- README.md
> Add polyrag to readme

- src/service/service.py
- src/streamlit_app.py
use streaming to get sub agent output. nests sub agent tool calls inside status containers using popovers. Agent ouptut can have any number of tool calls and AI messages ![image](https://github.com/user-attachments/assets/5d360f4e-0c80-432a-aeb1-0a74a8af030c)![image](https://github.com/user-attachments/assets/12dd0ce4-6e08-489a-9adf-cf9f11929c4d)
> Adds sub graph/agent output to streamlit frontend 

- .github/workflows/deploy.yml
- Resolves https://github.com/JoshuaC215/agent-service-toolkit/security/code-scanning/3
- Resolves https://github.com/JoshuaC215/agent-service-toolkit/security/code-scanning/4
- Resolves https://github.com/JoshuaC215/agent-service-toolkit/security/code-scanning/5
> Fix GHA deploy permissions

- README.md
- Improve consistency in project name formatting (agent-service-toolkit)
- Clarify uv installation options comment for better readability
- Improve Docker Compose version formatting with proper version prefix
- Fixed project name hyphenation consistency in comments
- Enhanced clarity of uv installation options comment
- Improved Docker Compose version reference formatting
These are minor formatting improvements that enhance the overall consistency and readability of the README documentation.
> Fix README formatting inconsistencies

- docs/RAG_Assistant.md
Updates `docs/RAG_Assistant.md` to correct hyperlinks to other files in the repository.
> Fix: RAG_Assistant.md file links
